import { AreaChart } from "@tremor/react";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

type Props = {
  series: Record<string, string>[];
  keyNames: string[];
  selectedApiKey?: string;
};

export function Chart({ series, keyNames, selectedApiKey }: Props) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Number of events generated by each API key</CardTitle>
      </CardHeader>
      <CardContent>
        <AreaChart
          className="h-72 mt-4"
          data={series}
          index="createdAt"
          categories={selectedApiKey ? [selectedApiKey] : keyNames}
        />
      </CardContent>
    </Card>
  );
}
