import {
  BarChart3,
  Building,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  ClipboardCopy,
  CreditCard,
  Edit3,
  FileCode,
  Hash,
  Key,
  Laptop,
  Moon,
  Plus,
  SunMedium,
  Trash2,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  overview: BarChart3,
  projects: FileCode,
  organization: Building,
  hash: Hash,
  plus: Plus,
  trash: Trash2,
  edit: Edit3,
  key: Key,
  clipboardCopy: ClipboardCopy,
  clipboardCheck: ClipboardCheck,
  arrowRight: ChevronRight,
  arrowLeft: ChevronLeft,
  check: Check,
  creditCard: CreditCard,
};
